/** 後臺用戶列表 **/
CREATE TABLE IF NOT EXISTS admins ( 
    id INT UNSIGNED NOT NULL AUTO_INCREMENT,
    name VARCHAR(20) NOT NULL DEFAULT '' COMMENT '登錄名稱',
    password CHAR(32) NOT NULL DEFAULT '' COMMENT '登錄密碼',
    last_ip VARCHAR(32) NOT NULL DEFAULT '' COMMENT '最後IP',
    state TINYINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '狀態',
    login_count INT UNSIGNED NOT NULL DEFAULT 0 COMMENT '登錄次數',
    last_login INT UNSIGNED NOT NULL DEFAULT 0 COMMENT '上次登錄時間',
    created INT UNSIGNED NOT NULL DEFAULT 0 COMMENT '創建時間',
    updated INT UNSIGNED NOT NULL DEFAULT 0 COMMENT '修改時間',
    INDEX(name),
    PRIMARY KEY(id)
);
