ALTER TABLE videos ADD COLUMN category_id INT UNSIGNED DEFAULT 0 COMMENT '分类编号';
ALTER TABLE videos ADD COLUMN tag_ids VARCHAR(500) NOT NULL DEFAULT '' COMMENT '标签编号';

ALTER TABLE videos ADD COLUMN author_id INT UNSIGNED DEFAULT 0 COMMENT '作者编号';

ALTER TABLE videos ADD COLUMN url VARCHAR(200) NOT NULL DEFUALT '' COMMENT '播放地址';
